### ISSUE TITLE
Discord bot tie in

### ISSUE THREAD

**Issue by Stew-85996** [Soyvolon/FiveOhFirstDataCore#15]
Adding a bot that sends messages to users when an event or reminder is happening.

Disclaimer, I don't know how bots work.

**Comment by Soyvolon** [comment]
In addition, the Discord bot would be able to automatically assign roles to Discord members when such roles are needed, such as slot and qualification changes.

**Comment by Soyvolon** [comment]
Completed as of 05147ee
